### PR TITLE
fix some inconsistencies in the README

### LINKED ISSUE #71: Some broken things for first timers
First of all, thanks for taking up the challenge and democratising this wunderful model.

encodec_24khz-d7cc33bc.th doesn't download for me

```
Downloading: "https:/dl.fbaipublicfiles.com/encodec/v0/encodec_24khz-d7cc33bc.th" to /Users/tatsch/.cache/torch/hub/checkpoints/encodec_24khz-d7cc33bc.th
Traceback (most recent call last):
  File "/Users/tatsch/workspace/bark.cpp/download_weights.py", line 41, in <module>
    state_dict = torch.hub.load_state_dict_from_url(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/hub.py", line 746, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/opt/homebrew/lib/python3.11/site-packages/torch/hub.py", line 611, in download_url_to_file
    u = urlopen(req)
        ^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 516, in open
    req = meth(req)
          ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1272, in do_request_
    raise URLError('no host given')
urllib.error.URLError: <urlopen error no host given>
```
curl -o models/encodec_24khz-d7cc33bc.th  https://dl.fbaipublicfiles.com/encodec/v0/encodec_24khz-d7cc33bc.th

vocab.txt also isnt there for me in models, maybe related to  the aforementioned issue

curl -o models/vocab.txt https://huggingface.co/suno/bark/blob/main/vocab.txt

but I guess its the wrong one because when I run it

```
bark_model_load: reading bark vocab
bark_vocab_load: wrong voculary size (305 != 119547)
bark_model_load: invalid model file './ggml_weights//ggml_vocab.bin' (bad text)
main: failed to load model from './ggml_weights/'

```

also the call in the readme should be 

`./main -m ./ggml_weights/ -p "this is an audio"
`
instead of 

`./main -m ./models/ggml_weights/ -p "this is an audio"
`
for the default folder structure.

### PR DESCRIPTION
**Pull request by jmtatsch**
partially fixes #71

### CODE REVIEW

**Review by PABannier — APPROVED** [review]

**Comment by PABannier** [comment]
Thanks @jmtatsch !

**Comment by jmtatsch** [comment]
Always happy to help.
Could you please point me to the correct vocab.txt?

**Comment by PABannier** [comment]
@jmtatsch You can obtain it by downloading the tokenizer `bert-multilingual-case` from HuggingFace. This is what bark uses. I'm wondering if I shouldn't upload it directly in `ggml_weights`. At least for now since we only support bark. WDYT?

**Comment by jmtatsch** [comment]
I always like it as easy as possible for the end user which should net the most users and thus the most contributions.
Also it reduces the potential amount of issues the user will open up ;)

**Pull request merged**
