### PR TITLE
Export function for dll in bark.h

### PR DESCRIPTION
**Pull request by vinovo**
This PR allows function to be exported for dynamic library on Windows.

### CODE REVIEW

**Comment by PABannier** [comment]
Hello @vinovo ! Thanks for the PR, I let you fix the CIs :)

**Comment by vinovo** [comment]
> Hello @vinovo ! Thanks for the PR, I let you fix the CIs :)

yeah I will look into it.

**Comment by vinovo** [comment]
@PABannier build now succeed on local, could try the CI again.

**Comment by PABannier** [comment]
Thanks @vinovo !

**Pull request merged**
